import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import Post from "@/components/Posts";
import { sanityClient } from "@/sanity";


const inter = Inter({ subsets: ["latin"] });

export default function Home({posts}) {
  
  return (
    <>
      <Head>
        <title>Medium Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen flex flex-col items-center">
        <Banner />
        <Post posts={posts}/>
      </div>
    </>
  );
}

export const getServerSideProps = async () => {
const query = `
*[_type == 'post']{
_id,
title,
  content,
  readtime,
slug,
author->{
name,
image
},
category,
publishedAt,
mainImage,
description
}

`;

      const posts = await  sanityClient.fetch(query)

      return {
        props : {
          posts,
        }
      }
}
